### ISSUE TITLE
Trouble using the script

### ISSUE THREAD

**Issue by frukbachers** [thebwt/makePlace-export#1]
Installed python, downloaded findItem.py, edited file location in, ran the script, nothing happens, except a quick flash as if a window quickly opens and closes.

Expected the behavior: some sort of results screen, save dialogue or file creation in the directory the script was run on.

Am I missing something?

**Comment by thebwt** [comment]
Are you running it from a cli or just like double clicking it?

**Comment by frukbachers** [comment]
Thanks for the quick reply: I had a misconception using the script. I have no experience with python whatsoever so for initial troubleshooting I just edited the "Filepath of the save file" with the absolute path of my savefile in both linux and windows and it didn't work. Searching in the makeplace discord further made it clear how to use it:

On Windows, I opened command prompt and navigated to the location of my savefile, copied the script there. Then i removed 

#!/bin/python

from the beginning of the script using a text editing program (as a user from the discord suggested). Then, I typed

py findItem.py Save.json

and it parsed correctly.

**Comment by thebwt** [comment]
Yea.... I really need to work on a web based thing to do this.... 

There's always tomorrow!
